server:
  port: 8888
  servlet:
    context-path: /api/
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-n2ibs5wa.sql.tencentcdb.com:28506/dewu?useSSL=false&characterEncoding=utf8
    username: dewu
    password: password@123
    driver-class-name: com.mysql.jdbc.Driver
