server:
  port: 8888
  servlet:
    context-path: /api/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dewu?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
